### ISSUE TITLE
网页和内容优化

### ISSUE THREAD

**Issue by rootsongjc** [cloudnativeto/sig-envoy#4]
今天 Envoy SIG 的网页已成功发布，不过关于还有些问题需要修改和优化的点，我暂时列举如下，还有更多请补充。

1. 首页的这个部分比较难看，需要修改下 icon 和显示链接，没必要加上那些“更多...”，而是可以将这些链接直接放到 icon 下方的文字中。
![image](https://user-images.githubusercontent.com/3328185/94108158-622b8400-fe71-11ea-8c44-0fa4bc88b0e3.png)
2. favicon 需要修改为云原生社区的
3. footer 里的信息需要再完善下，起码加上云原生社区的首页链接及社区的公众号二维码
4. 留言功能请跟云原生社区主站统一
5. [社区页面](https://cloudnative.to/sig-envoy/docs/community/)作为一个单页，重新调整下布局，去掉左侧的 sidebar，
6. [博客页面](https://cloudnative.to/sig-envoy/blog)也没必要留个 sidebar
7. [文档页面](https://cloudnative.to/sig-envoy/docs)是做什么用的？

@helight @zyfjeff

**Comment by helight** [comment]
嗯，这部分我们来优化

**Comment by rootsongjc** [comment]
另外还要麻烦你们写一篇博客提交到社区官网上，作为一个 Envoy SIG 成立的声明，该博客也会发布到云原生社区的微信公众号上。最好能在下周完成。

**Comment by helight** [comment]
这个前一段时间不是小马哥写了一个吗？还是要重新写一个？

**Comment by rootsongjc** [comment]
https://cloudnative.to/blog/sig-envoy-announcement/
这一篇写的过于简单了，你们可以提交个 PR 在补充下。
@lhb008 @helight 你们商量下看吧。
虽然博客是发了，不过还没有对外宣传这个。

**Comment by helight** [comment]
好的，我们再整理一下

**Comment by majinghe** [comment]
把招募翻译志愿者的信息我加一下。这样就是成立暨翻译招募，一起发。这块儿我先改一下，然后你们一起帮review一下。

**Comment by rootsongjc** [comment]
另外所有的网站更新都通过提交 PR 的方式进行，我启用了 merfigy，只有 reviewer approve PR 后才才可以合并。
